# Generated by Django 4.0.4 on 2022-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_descricao_do_projeto_projeto_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem_ilustrativa',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
    ]
