# Generated by Django 4.0.4 on 2022-04-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projeto_imagem_ilustrativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagem_ilustrativa',
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
